class Config():
    def __init__(self):
        self.cuffmerge='/storage_wut/test_chen/software/cufflinks-2.2.1.Linux_x86_64/cuffmerge'
        self.cuffcompare='/storage_wut/test_chen/software/cufflinks-2.2.1.Linux_x86_64/cuffcompare'
        self.cufflinks='/storage_wut/test_chen/software/cufflinks-2.2.1.Linux_x86_64/cufflinks'
        self.gtf_to_sam='/storage_wut/test_chen/software/cufflinks-2.2.1.Linux_x86_64/gtf_to_sam'
        self.sort='sort'
        self.blastx='/storage_wut/01Software/Anaconda/anaconda3/bin/blastx'
        self.framefinder='/storage_wut/01Software/cpc-0.9-r2/libs/estate/bin/framefinder'
        self.svm_scale='/storage_wut/01Software/cpc-0.9-r2/libs/libsvm/libsvm-2.81/svm-scale'
        self.svm_predict2='/storage_wut/01Software/cpc-0.9-r2/libs/libsvm/libsvm-2.81/svm-predict2'
        self.samtools='/storage_wut/01Software/Anaconda/anaconda3/bin/samtools'
        self.fram_model ='/storage_wut/01Software/cpc-0.9-r2/data/framefinder.model'
        self.lib_range ='/storage_wut/01Software/cpc-0.9-r2/data/libsvm.range'
        self.lib_model ='/storage_wut/01Software/cpc-0.9-r2/data/libsvm.model0'
        self.nr_database='/storage_wut/database/01.nt_nr/nr/20180201/Mammals.fa'